name: call-stokenet
on:
  workflow_dispatch:

jobs:
  call-decrypt-workflow:
    uses: ankushjha-aj/SOPS-ECHO/.github/workflows/sops-reusable.yml@main
    with:
      aws-region: "eu-central-1"  
      file-to-decrypt: "ashwini.enc.yml"
    secrets: 
      AWS_ACCESS_KEY: ${{ secrets.STOKENET_AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.STOKENET_AWS_SECRET_KEY }} 
